### ISSUE TITLE
Config.CheckOwnership

### ISSUE THREAD

**Issue by newbieusecode** [BryanLTU/bryan_mazebank_garage#1]
it doesn't work for qbcore. it cannot check if this car is yours

**Comment by BryanLTU** [comment]
Could you perhaps provide me with an error that you're receiving?

**Comment by newbieusecode** [comment]
https://streamable.com/4rtegg

I'm very sorry because I'm not good at English. I have screen recorded the problem I am having

**Comment by BryanLTU** [comment]
Could you try changing these lines in [server/functions.lua](https://github.com/BryanLTU/bryan_mazebank_garage/blob/4f4caca8d9816a1cbd109fc97162555048def101/server/functions.lua#L87-L89?plain=1).

From:
```lua
local result = MySQL.query.await('SELECT citizenid FROM player_vehicles WHERE citizenid = ?', {
    _GetPlayerIdentifier(source)
})
```
To:
```lua
local result = MySQL.query.await('SELECT license FROM player_vehicles WHERE license = ?', {
    _GetPlayerIdentifier(source)
})
```
The key difference is `citizenid` -> `license`

And tell me if this fixes the issue. It's a bit difficult for me because I don't have a QB-Core server to test this on.

**Comment by newbieusecode** [comment]
![image](https://github.com/BryanLTU/bryan_mazebank_garage/assets/152671804/3e49343d-eb96-409a-8dd0-cc65b7c58ec7)
there was an error

**Comment by BryanLTU** [comment]
You replaced the wrong lines or something, because what you did is executing ESX SQL. It's trying to access `owned_vehicles` table which is on ESX servers

**Comment by newbieusecode** [comment]
![image](https://github.com/BryanLTU/bryan_mazebank_garage/assets/152671804/66fd3870-601d-4c35-ad30-205d8a570ca9)
before I add your fix. I redownloaded the new scripts and cleared the cache. I only replaced 3 lines
Config.CheckOwnership = true
Config.UseTarget = false

**Comment by BryanLTU** [comment]
And did you change `Config.Framework = 'qbcore'`?

**Comment by newbieusecode** [comment]
I have changed

**Comment by BryanLTU** [comment]
That was my fault, pushed a new update to fix that error (https://github.com/BryanLTU/bryan_mazebank_garage/commit/669d813a1c3d8d711644160c6bc93dae66828ccf). Re-download and try again to see if it works. Try at first with the lines I sent you.

**Comment by newbieusecode** [comment]
I have tested very carefully and the problem after fixing the error is as follows:
When I access the server and buy a parking garage then I lockpick a vehicle from the npc to send it in and it works normally (it checked player_vehicles) and won't let me deposit it. But after I went to the store to buy a car, when I sent the car I owned, the error continued to occur. it did not check player_vehicles with the lockpick vehicle from npc.

**Comment by newbieusecode** [comment]
https://www.youtube.com/watch?v=mCNFzK3IpPY

Here is the video I recorded.

**Comment by BryanLTU** [comment]
Sorry, I didn't entirely understand you. Here's what I'm understanding from you:
- At first, storing owned vehicle works
- Then when you want to store an NPC vehicle (that you do not own), it should not let you, but still stores it.

Is this correct?

**Comment by newbieusecode** [comment]
Yes sir. I recorded the video above. sorry because I can't upload it to streamlab

**Comment by newbieusecode** [comment]
![image](https://github.com/BryanLTU/bryan_mazebank_garage/assets/152671804/39a62e02-f22d-4c10-9ee3-e7658236bc80)
1 more error. After someone else bought the garage, an error appeared?

**Comment by BryanLTU** [comment]
Hello,
Please check out the latest release and let me know if it fixes the issue.

Have a wonderful day!
