### ISSUE TITLE
owner garage error

### ISSUE THREAD

**Issue by newbieusecode** [BryanLTU/bryan_mazebank_garage#3]
![image](https://github.com/BryanLTU/bryan_mazebank_garage/assets/152671804/085fa8cf-63ff-4d7e-8497-151f69d02f23)

The problem with the vehicle's owner has been resolved. Added new error when 2 people buy garage

**Comment by BryanLTU** [comment]
Thanks for reporting that. But it seems that, those 2 people are the same person with the same license. If you're using some sort of multicharacter script, then sorry I won't be able to help you.

**Comment by newbieusecode** [comment]
yeah I get it. I replaced it with citizenid. and everything was fixed. a nice script thanks for sharing

**Comment by Tigo8811** [comment]
can you send te code how to fix it because i got the same problem
